Adding docs
qiboteam/qibotn pull request #35
Opened 2024-02-29 01:16 UTC by Vinitha-balachandran

To add doc files

2024-02-29 06:15 UTC, alecandido commented
TODO: point this PR to the branch of #24 (I can't do immediately, because there is no new commit wrt that one)

Motivation: having a meaningful diff (i.e. a meaningful view in the *Files changed* tab)

2024-02-29 08:41 UTC, Vinitha-balachandran commented
> TODO: point this PR to the branch of #24 (I can't do immediately, because there is no new commit wrt that one)
> 
> Motivation: having a meaningful diff (i.e. a meaningful view in the _Files changed_ tab)

I have rebased PR to  qibotn_integration branch.

2024-02-29 10:26 UTC, liweintu commented
Heads-up:
This PR is branched out from PR #24, that's why it has all the historical commits from branch `qibotn_integration`.  We need to be careful about the two PR branches being merged into `main`.

2024-02-29 11:14 UTC, alecandido commented
> Heads-up: This PR is branched out from PR #24, that's why it has all the historical commits from branch `qibotn_integration`. We need to be careful about the two PR branches being merged into `main`.

I noticed, and @Vinitha-balachandran changed the base branch.

The worst it can happen now is that this will be merged in #24, increasing the diff. But it would not be a big deal anyhow, since this is mostly contained in a new folder.

2024-03-01 06:44 UTC, alecandido commented
@liweintu and @Vinitha-balachandran is this completed?

I already had a look to the changes, and I have nothing major to amend.

The only piece that is clearly missing are the extracted docstrings. You could follow the Qibolab example:
https://github.com/qiboteam/qibocal/blob/06457b828f0f8e4c1878266ea48924e6503b15a4/doc/source/conf.py#L126-L131
https://github.com/qiboteam/qibocal/blob/06457b828f0f8e4c1878266ea48924e6503b15a4/doc/source/index.rst?plain=1#L52-L56
(even though I'd `gitignore` the resulting folder, despite Qibocal is not doing it... but maybe it will!)

Other than that, I see that the PR is still draft, so I assume it to be work-in-progress. Is it correct?

2024-03-01 07:47 UTC, liweintu commented
> I noticed, and @Vinitha-balachandran changed the base branch.
> 
> The worst it can happen now is that this will be merged in #24, increasing the diff. But it would not be a big deal anyhow, since this is mostly contained in a new folder.

Indeed. Now that PR #35 is planned to be merged into the branch of PR #24 , we'll do PR #35 first. Then, followed by PR #24 . This should pick up all the commits from both branches.

2024-03-01 07:57 UTC, alecandido commented
> Indeed. Now that PR #35 is planned to be merged into the branch of PR #24 , we'll do PR #35 first. Then, followed by PR #24 . This should pick up all the commits from both branches.

That's acceptable, but if possible, I'd prioritize #24 first.

The rationale is that this is an addition, so it is not strictly needed for #24, and having #24 in `master` would also improve the testing for the PR in `qibo` itself.

2024-03-01 08:00 UTC, alecandido commented on .github/workflows/rules.yml
This workflow is for testing, please restore it to its previous state.

We have dedicated workflows for the docs, and you have to invoke the correct reusable one (you're still calling the test workflow, despite installing only docs dependencies).

You could follow the example of `qibo` itself:
https://github.com/qiboteam/qibo/blob/master/.github/workflows/publish.yml

2024-03-01 08:14 UTC, Vinitha-balachandran commented on .github/workflows/rules.yml
My bad, still in the learning stage. Has restored the file.

2024-03-01 09:01 UTC, liweintu commented
> That's acceptable, but if possible, I'd prioritize #24 first.
> 
> The rationale is that this is an addition, so it is not strictly needed for #24, and having #24 in `master` would also improve the testing for the PR in `qibo` itself.

Yup, fair enough. We'll go through the remaining points in #24 and finish it up first.

2024-03-01 10:48 UTC, Vinitha-balachandran commented
> @liweintu and @Vinitha-balachandran is this completed?
> 
> I already had a look to the changes, and I have nothing major to amend.
> 
> The only piece that is clearly missing are the extracted docstrings. You could follow the Qibolab example: https://github.com/qiboteam/qibocal/blob/06457b828f0f8e4c1878266ea48924e6503b15a4/doc/source/conf.py#L126-L131 https://github.com/qiboteam/qibocal/blob/06457b828f0f8e4c1878266ea48924e6503b15a4/doc/source/index.rst?plain=1#L52-L56 (even though I'd `gitignore` the resulting folder, despite Qibocal is not doing it... but maybe it will!)
> 
> Other than that, I see that the PR is still draft, so I assume it to be work-in-progress. Is it correct?

I have included the missing part.

2024-03-01 11:04 UTC, liweintu requested changes

2024-03-01 11:04 UTC, liweintu commented on docs/source/index.rst
> +    api-reference/modules
We need to put in the right content based on the basic source files available now.

2024-03-01 13:12 UTC, liweintu commented
Hi @alecandido , I see all comments are generally addressed, do you think it's good to merge this RP?

2024-03-01 15:39 UTC, alecandido commented on docs/source/conf.py
> +    apidoc.main(["--no-toc", "--module-first", "-o", str(docs_dest), str(package)])
This is just defining the function, but running it. It has to be registered in the `setup()` function, which is automatically called by Sphinx (if defined).

https://github.com/qiboteam/qibocal/blob/06457b828f0f8e4c1878266ea48924e6503b15a4/doc/source/conf.py#L139

2024-03-01 15:41 UTC, alecandido commented on docs/source/index.rst
> +
You should also add the generated API to the `toctree` (its own section).

If a document is not mentioned in any `toctree`, it is not included in the resulting documentation (i.e. docs are discovered through `toctree`s, not directly files).
https://github.com/qiboteam/qibocal/blob/06457b828f0f8e4c1878266ea48924e6503b15a4/doc/source/index.rst?plain=1#L52-L57

2024-03-01 15:42 UTC, alecandido commented on docs/source/index.rst
> +
Please, follow the general Qibo template, and add the usual sections.

https://github.com/qiboteam/qibocal/blob/06457b828f0f8e4c1878266ea48924e6503b15a4/doc/source/index.rst?plain=1#L59-L66

2024-03-01 15:44 UTC, liweintu commented
> That's acceptable, but if possible, I'd prioritize #24 first.
> 
> The rationale is that this is an addition, so it is not strictly needed for #24, and having #24 in `master` would also improve the testing for the PR in `qibo` itself.

Now that PR #24 has been merged into `main`, I changed the target branch to `main` as per the exact rationale above.

2024-03-01 15:44 UTC, alecandido commented
The lock file was outdated. Every time you change dependencies in `pyproject.toml` (even groups and extras), please run `poetry lock`.

2024-03-01 15:45 UTC, alecandido commented
> Now that PR #24 has been merged into `main`, I changed the target branch to `main` as per the exact rationale above.

@scarrazza could you set the repo to automatically delete merged branches, and reroute existing PRs?

2024-03-01 16:01 UTC, liweintu commented on docs/source/conf.py
> +    apidoc.main(["--no-toc", "--module-first", "-o", str(docs_dest), str(package)])
Following the qibocal example, added the `setup()` function for Sphinx to call.

2024-03-01 16:11 UTC, liweintu commented on docs/source/index.rst
> +
Added the usual sections as per the Qibo template.

2024-03-01 16:20 UTC, liweintu commented on docs/source/index.rst
> +
Added the `toctree` section for the generated API.

2024-03-01 16:30 UTC, alecandido commented
Missing **unused** dependency

```
❯ make html
Running Sphinx v5.3.0

Extension error:
Could not import extension nbsphinx (exception: No module named 'nbsphinx')
make: *** [Makefile:20: html] Error 2
```

Please, try to install from scratch with `poetry install --with docs`, and then run `cd docs; make html`, to test the generation is happening correctly.

2024-03-01 16:40 UTC, alecandido commented
```
.../qibotn/docs/source/index.rst:46: ERROR: Error in "toctree" directive:
invalid option block.
                                                                                                       
.. toctree::
   :maxdepth: 2
   :caption: Introduction
   Installation
   Quickstart
.../qibotn/docs/source/index.rst:44: ERROR: Document or section may notbegin with a transition.
```

2024-03-01 16:52 UTC, liweintu commented
> ```
> .../qibotn/docs/source/index.rst:46: ERROR: Error in "toctree" directive:
> invalid option block.
>                                                                                                        
> .. toctree::
>    :maxdepth: 2
>    :caption: Introduction
>    Installation
>    Quickstart
> .../qibotn/docs/source/index.rst:44: ERROR: Document or section may notbegin with a transition.
> ```

After trying `poetry install --with docs`, I re-produced the error, will follow some reference from `qibo` or `qibocal` to fix it.

2024-03-01 17:42 UTC, liweintu commented
> Missing **unused** dependency
> 
> ```
> ❯ make html
> Running Sphinx v5.3.0
> 
> Extension error:
> Could not import extension nbsphinx (exception: No module named 'nbsphinx')
> make: *** [Makefile:20: html] Error 2
> ```
> 
> Please, try to install from scratch with `poetry install --with docs`, and then run `cd docs; make html`, to test the generation is happening correctly.

After re-organising the files into the subfolders as per Qibo document convention, `make html` can work.

However, I encountered a hanging issue of `poetry install` in some GPU Ubuntu machine. In some other machine (e.g. MacBook), `poetry install` works fine. @Tankya2 also experienced this. It seems to be a known issue as per here: python-poetry/poetry#3365. Did you ever encounter this hanging issue? @alecandido

2024-03-01 17:44 UTC, scarrazza commented
> @scarrazza could you set the repo to automatically delete merged branches, and reroute existing PRs?

Done.

2024-03-01 21:47 UTC, alecandido commented
> It seems to be a known issue as per here: [python-poetry/poetry#3365](https://github.com/python-poetry/poetry/issues/3365). Did you ever encounter this hanging issue? @alecandido

Yes, it was a common problem around Poetry v1.1.2 and similar.
By now (Poetry v1.8 released few days ago, I'm also using v1.7.1), I've never encountered any longer.

If the version of Poetry you're using, I'd suggest upgrading it (with the various methods for installation listed in the docs, e.g. `pipx`, but it's just an example), and deleting the cache (`poetry cache clear PyPI`, or `poetry cache clear <id>`, where you could find `<id>` running `poetry cache list`).

@liweintu

2024-03-01 21:52 UTC, alecandido approved these changes
By now, docs are compiling in a fresh new repo without raising errors nor warnings

2024-03-01 21:52 UTC, merged