Update tn
qiboteam/qibotn pull request #74
Opened 2024-10-04 07:24 UTC by Tankya2

Hi, 

This PR is to address issue #36. 

Added memory management code and set the Pathfinding model used to CUTENSOR.

2024-10-04 12:50 UTC, alecandido requested changes
The `eval.py` contains highly duplicated code, and this is manifest in this PR, since the same update has been repeated over and over.

Before merging this PR, increasing even more the maintenance burden, it would be worth to refactor the `eval.py` file (in this, or even in another PR), to avoid incurring is such a redundant diff.

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/backends/cutensornet.py
> +        import cuquantum
While do you now need this, without using it anywhere? (i.e. there are no other lines in this file's diff...)

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> +    del network
What is this for? Why do you now need it?

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> +    del network
Assuming it is for memory management

> Deletion of a name removes the binding of that name from the local or global namespace, depending on whether the name occurs in a [global](https://docs.python.org/3/reference/simple_stmts.html#global) statement in the same code block. If the name is unbound, a [NameError](https://docs.python.org/3/library/exceptions.html#NameError) exception will be raised.
> https://docs.python.org/3/reference/simple_stmts.html#the-del-statement

> del x doesn’t directly call x.__del__() — the former decrements the reference count for x by one, and the latter is only called when x’s reference count reaches zero. 
> https://docs.python.org/3/reference/datamodel.html#object.__del__

So, unless it is exactly documented that you should apply `del network` before `.free_all_blocks()` (and even in that case, we should make sure that the underlying `.__del__()` is called when you wish), it doesn't make much or no difference wrt just waiting for the `return`, since the `network` name would get anyhow out of scope, and the `.__del__()` method would be called. This only if no other references are kept in the returned objects, which is also a condition for the current `del network` statement to work - so nothing would change from that point of view.

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> +        operands = None
What's the actual purpose of this?

If `rank != 0`, `qibo_circ` is fully ignored...

Even if it is somehow meaningful (I'm not seeing how, but that may be my limitation), the result could only be trivial, so you could even return immediately, without executing all the other operations...

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> +    import cuquantum.cutensornet as cutn
Any reason to keep the imports within the functions? (instead of top-level)

I know it was like this even before this PR...

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> -    device_id = rank % getDeviceCount()
Do you remember why it was repeated before?

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> -    device_id = rank % getDeviceCount()
The comment may be still useful, and you could lift to the line above.

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> +    import cuquantum.cutensornet as cutn
Same as above

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> +    del network
Same as above

2024-10-04 12:50 UTC, alecandido commented on src/qibotn/eval.py
> +        operands = myconvertor.state_vector_operands()
These lines are definitely duplicated now...

Maybe you intended to drop those above.

2024-10-30 03:12 UTC, Tankya2 commented on src/qibotn/backends/cutensornet.py
> +        import cuquantum
This was used to get the CUDA_TYPES in line 70 and the version in line 65. I have changed to importing the required attribute direct instead.

2024-10-30 03:18 UTC, Tankya2 commented on src/qibotn/eval.py
> +        operands = myconvertor.state_vector_operands()
Yes these are duplicated.

2024-10-30 05:50 UTC, Tankya2 commented on src/qibotn/eval.py
> +        operands = None
Line 86 (operands = comm.bcast(operands, root)) broadcast the operands created in Rank 0 to all other ranks. Each rank needs the same starting operands for computation.

2024-10-30 06:08 UTC, Tankya2 commented on src/qibotn/eval.py
> +    import cuquantum.cutensornet as cutn
The reason was that not all functions require the import, specifically dense_vector_tn(), expectation_pauli_tn(), dense_vector_mps(), pauli_string_gen(). Do you think it is better to bring them to the top-level?

2024-11-20 09:54 UTC, liweintu commented on src/qibotn/eval.py
> +    del network
Removed these unnecessary deletion because automatic deletion is implicitly already there at the function end.

2025-01-16 04:43 UTC, scarrazza commented
@alecandido @Tankya2 what is the plan for this PR?

2025-01-16 07:20 UTC, Tankya2 commented
> @alecandido @Tankya2 what is the plan for this PR?

Hi @scarrazza, @alecandido , @liweintu , I believe most issues in this PR have been addressed. The remaining concern is the presence of duplicated code across various computation modes. I propose to close this PR first if there are no other further issues and to tackle these duplicated codes in another PR.

2025-01-16 10:12 UTC, liweintu commented
I tested this PR branch on ASPIRE 2A+, using `test_cuquantum_cutensor_backend.py`. Most cases passed, but there's 1 assertion failure below.

```py
        # Test Cuquantum
        cutn_time, result_tn = time(
            lambda: qibotn.eval.dense_vector_tn(qibo_circ, dtype).flatten()
        )

>       assert 1e-2 * qibo_time < cutn_time < 1e2 * qibo_time
E       assert 0.38179754093289375 < (100.0 * 0.00212192814797163)
```

Seems the time taken is too long to pass the assertion? @Tankya2

2025-01-16 12:16 UTC, alecandido commented
My main concern was that the code was extended, introducing even further duplication, without reducing the existing one.

Tests and performance benchmarks are not automated, so little can be said.

However, if you manually test the code, and this is needed soon, of course feel free to proceed. Just take note of the project needs, and schedule them for later.

2025-08-27 04:03 UTC, Tankya2 commented on tests/conftest.py
> +# BACKENDS = ["qmatchatea"]
Error was encountered when I include "qmatchatea" in the BACKENDS list which causes pytest to fail. This error is similar to the one reported in issue #98. Will add this back once that issue is resolved.  @alecandido @liweintu @Vinitha-balachandran @scarrazza

2025-08-28 09:55 UTC, liweintu commented on tests/conftest.py
> +# BACKENDS = ["qmatchatea"]
As per our Wednesday meeting, we can check whether it's caused by a mismatch with `dtype`. If so, once the mismatch is fixed, we can add it back to the test.

2025-08-29 06:37 UTC, Tankya2 commented on tests/conftest.py
> +# BACKENDS = ["qmatchatea"]
I did a quick check, it seems to be due to circular import. The filename qmatchatea.py is same as the actual package name (import qmatchatea inside qmatchatea.py) so when one tries to initialize the backend it leads to attribute error because it tries to call a method in package qmatchatea but python is looking for the method in qmatchatea.py.

2025-08-29 06:42 UTC, Tankya2 commented
Hi @alecandido and @liweintu I have made quite major changes since the last review (based on comments and also due to standardizing with qmatchatea) so some of the previous comments might be outdated. Please help to look at it again and let me know what else needs to be done. I am also attaching the screenshots of the pytest I have done on my machine. @scarrazza @Vinitha-balachandran 
<img width="1005" height="211" alt="Screenshot 2025-08-29 at 2 18 54 PM" src="https://github.com/user-attachments/assets/cf100b15-a08e-455d-921f-ca2690e515ff" />
<img width="998" height="663" alt="Screenshot 2025-08-29 at 2 26 09 PM" src="https://github.com/user-attachments/assets/5e434ac7-d60c-444e-af2c-b77b862d821b" />

2025-09-02 03:46 UTC, Vinitha-balachandran commented
Tested the PR on Aspire2a. Pytests are passing as shown in the screenshot by @Tankya2.

2025-09-02 09:47 UTC, liweintu requested changes
Added a few comments for minor changes.

2025-09-02 09:47 UTC, liweintu commented on src/qibotn/eval.py
> +        # print(f"Adding term: {final_term}")  # Debugging output
Remove the debugging print-out?

2025-09-02 09:47 UTC, liweintu commented on src/qibotn/eval.py
> +    # print(f"Hamiltonian Form After Summation: {hamiltonian_form}")
Remove the debugging print-out?

2025-09-02 09:47 UTC, liweintu commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_1 = {
Replace `1` with a self-explanatory naming to denote this test setting?

2025-09-02 09:47 UTC, liweintu commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_2 = {
Replace `2` with a self-explanatory naming to denote this test setting?

2025-09-02 09:47 UTC, liweintu commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_1 = {
Replace `1` with a self-explanatory naming to denote this test setting?

2025-09-02 09:47 UTC, liweintu commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_2 = {
Replace `2` with a self-explanatory naming to denote this test setting?

2025-09-02 09:47 UTC, liweintu commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_3 = {
Replace `3` with a self-explanatory naming to denote this test setting?

2025-09-02 09:47 UTC, liweintu commented on tests/test_cuquantum_cutensor_mpi_backend.py
> +            exact_expval.item(), float(result_tn[0]), abs_tol=1e-7
Can extract the `1e-7` value to a configurable variable for easy configuration, in case we have different tolerance requirements in our future tests?

2025-09-03 01:27 UTC, Tankya2 commented on src/qibotn/eval.py
> +        # print(f"Adding term: {final_term}")  # Debugging output
yes can be removed

2025-09-03 01:28 UTC, Tankya2 commented on src/qibotn/eval.py
> +    # print(f"Hamiltonian Form After Summation: {hamiltonian_form}")
yes removed

2025-09-03 02:19 UTC, Tankya2 commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_1 = {
Sure I have change the description

2025-09-03 02:19 UTC, Tankya2 commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_1 = {
Sure I have change the description

2025-09-03 02:19 UTC, Tankya2 commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_3 = {
Sure I have change the description

2025-09-03 02:19 UTC, Tankya2 commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_2 = {
Sure I have change the description

2025-09-03 02:20 UTC, Tankya2 commented on tests/test_cuquantum_cutensor_backend.py
> +    computation_settings_2 = {
Sure I have change the description

2025-09-03 02:21 UTC, Tankya2 commented on tests/test_cuquantum_cutensor_mpi_backend.py
> +            exact_expval.item(), float(result_tn[0]), abs_tol=1e-7
Sure I have made it a variable

2025-09-03 10:12 UTC, liweintu requested changes
Please refine the naming for the settings such that the styles of settings are self-explanatory.

2025-09-04 02:37 UTC, Tankya2 commented
> Please refine the naming for the settings such that the styles of settings are self-explanatory.

I have change the naming such that it is now more self explanatory.

2025-09-04 07:15 UTC, liweintu approved these changes

2025-09-04 08:47 UTC, alecandido commented on tests/conftest.py
> +# BACKENDS = ["qmatchatea"]
The error reported in #98 is actually different from the one described in the last comment, and it seems more likely to be related to a `qmatchatea` version mismatch (cf. [my last comment](https://github.com/qiboteam/qibotn/issues/98#issuecomment-3252532694)).

The circular import explanation is also inconsistent: when you `import` Python looks for the package name in the `PYTHONPATH` (and possibly other configured paths), which includes the current directory. This causes issue if I write a script:
```py
# ciao.py
import ciao
```
and run with `python ciao.py`.

However, this is not the case for `qibotn`, where it is certainly not expected that your `$PWD` corresponds to the folder containing `qmatchatea.py`. Thus, `import qmatchatea` will look in other possible paths, but not for that one.
When using packages, the only likely ways to cause circular imports are by using fully qualified or relative imports, i.e. `import qibotn.backends.qmatchatea` or `from . import qmatchatea`.

Would you post the error you are obtaining (the traceback)? Or just reintroduce `qmatchatea` among tested backends (in case it's now magically working)

2025-09-04 09:04 UTC, alecandido reviewed
I did not conduct a thorough inspection, and I already appreciate the effort to refactor the backend closer to the QMatcha one.

All in all, I gave some erratic suggestion about the code, for things which were easily identifiable to me.

However, despite the mentioned efforts, I still seem to identify lots of patterns in `eval.py`. Which, in turn, it keeps growing (as number of lines), while not exposing many more significant features (ok, in this case I could identify one new feature: support for Qibo Hamiltonians extending the observable domain, previously restricted to Pauli strings).

I would recommend scheduling some time to attempt refactoring (simplifying/deduplicating) the content of `eval.py`, before extending it much further.

In any case, I'm not asking for it immediately. Once the individual comments will be addressed, I will approve the PR.

2025-09-04 09:04 UTC, alecandido commented on src/qibotn/eval.py
> +    return network.contract(slices=slices)
Is this really needed?

You're essentially defining a function which aliases an existing method.
Why not calling directly the method?

2025-09-04 09:04 UTC, alecandido commented on src/qibotn/eval.py
> +    elif method == "NCCL":
If you already returned within the former branch, there is no need for `elif`. Just use 
```suggestion
    if method == "NCCL":
```

2025-09-04 09:04 UTC, alecandido commented on src/qibotn/eval.py
> +        return result
Moreover, what happens if it's neither `"MPI"` nor `"NCCL"`?

I would suggest to either restrict the possible set of options with an explicit error
```py
if x is "a":
    return ...
if x is "b":
    return ...
raise ValueError()
```
or pick a default
```py
if x is "a":
    return ...
return ...
```

When nothing is done, an implicit `None` will be returned. Which will cause an error subsequently.
If you're lucky, it will be an error right after. Otherwise, it will happen *somewhere*, making it harder to trace the source.

2025-09-04 09:04 UTC, alecandido commented on src/qibotn/eval.py
> +    print("Default hamiltonian: ", hamiltonian_form)
Leftover print?

2025-09-05 02:12 UTC, Tankya2 commented on tests/conftest.py
> +# BACKENDS = ["qmatchatea"]
Please see the screen shot of the error. 
<img width="751" height="186" alt="Screenshot 2025-09-05 at 10 03 24 AM" src="https://github.com/user-attachments/assets/0ca24f47-4e6d-4d17-af40-b7bd875a23f0" />
I see what you mean. I was confused then as I just did a quick check. What happen was when I was stepping through I see that the error occur in the QMatchaTeaBackend.__init__() and I thought it was calling it a second time and not the first time.
<img width="1503" height="1014" alt="Screenshot 2025-09-05 at 10 46 03 AM" src="https://github.com/user-attachments/assets/8908302b-df0e-4e4a-b639-e9d9e5883ee9" />
v1.4.3 QCBackend's init indeed don't have backend as an argument.
Thanks for pointing out my mistake!

2025-09-05 03:21 UTC, Tankya2 commented on src/qibotn/eval.py
> +    print("Default hamiltonian: ", hamiltonian_form)
Removed

2025-09-05 06:58 UTC, Tankya2 commented on src/qibotn/eval.py
> +        return result
Have added ValueError if neither type is given

2025-09-05 06:59 UTC, Tankya2 commented on src/qibotn/eval.py
> +    return network.contract(slices=slices)
Have change to direct calling

2025-09-05 07:05 UTC, Tankya2 commented
> I did not conduct a thorough inspection, and I already appreciate the effort to refactor the backend closer to the QMatcha one.
> 
> All in all, I gave some erratic suggestion about the code, for things which were easily identifiable to me.
> 
> However, despite the mentioned efforts, I still seem to identify lots of patterns in `eval.py`. Which, in turn, it keeps growing (as number of lines), while not exposing many more significant features (ok, in this case I could identify one new feature: support for Qibo Hamiltonians extending the observable domain, previously restricted to Pauli strings).
> 
> I would recommend scheduling some time to attempt refactoring (simplifying/deduplicating) the content of `eval.py`, before extending it much further.
> 
> In any case, I'm not asking for it immediately. Once the individual comments will be addressed, I will approve the PR.

Thanks for looking into it. I have responded to your comments. Please see if it is ok. As for the refactoring of eval.py, I will start an issue and look into it separately. Thanks!

2025-09-05 12:00 UTC, alecandido approved these changes

2025-09-08 02:13 UTC, merged